<a href="https://colab.research.google.com/github/biki-das369/Vector-Borne-Disease-Detection/blob/main/VectorDemo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
#from sklearn.preprocessing import LevelEncoder
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [ ]:
#loding the csv file
vector_data = pd.read_csv('/content/tain_final.csv')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
#print first 5 rows
vector_data.head()

sudden_fever  headache  mouth_bleed  nose_bleed  muscle_pain  joint_pain  \
0             0         1            1           1            1           0   
1             1         1            1           1            1           0   
2             0         1            0           1            0           0   
3             0         0            0           0            0           1   
4             1         0            0           0            1           1   

   vomiting  rash  diarrhea  swelling  ...  toe_inflammation  \
0         1     0         0         0  ...                 0   
1         1     1         1         0  ...                 0   
2         1     1         0         0  ...                 0   
3         1     1         0         0  ...                 0   
4         1     1         0         0  ...                 0   

   finger_inflammation  lips_irritation  itchiness  ulcers  toenail_loss  \
0                    0                0          0       0             0   
1                    0                0          0       0             0   
2                    0                0          0       0             0   
3                    0                0          0       0             0   
4                    0                0          0       0             0   

   speech_problem  bullseye_rash  Grayish_discolouration_of_skin    prognosis  
0               0              0                               0  Chikungunya  
1               0              0                               0  Chikungunya  
2               0              0                               0  Chikungunya  
3               0              0                               0  Chikungunya  
4               0              0                               0  Chikungunya  

[5 rows x 52 columns]

In [ ]:
#print last 5 rows
vector_data.tail()

sudden_fever  headache  mouth_bleed  nose_bleed  muscle_pain  joint_pain  \
105             1         0            0           0            0           0   
106             0         0            0           0            0           0   
107             0         1            0           0            0           0   
108             1         1            0           0            0           0   
109             1         1            0           0            0           0   

     vomiting  rash  diarrhea  swelling  ...  toe_inflammation  \
105         1     0         0         0  ...                 0   
106         1     0         0         0  ...                 0   
107         1     0         0         0  ...                 0   
108         1     0         0         0  ...                 0   
109         1     0         0         0  ...                 0   

     finger_inflammation  lips_irritation  itchiness  ulcers  toenail_loss  \
105                    0                0          0       0             0   
106                    0                0          0       0             0   
107                    0                0          0       0             0   
108                    0                0          0       0             0   
109                    0                0          0       0             0   

     speech_problem  bullseye_rash  Grayish_discolouration_of_skin  prognosis  
105               0              0                               1  Kala Azar  
106               0              0                               1  Kala Azar  
107               0              0                               1  Kala Azar  
108               0              0                               1  Kala Azar  
109               0              0                               1  Kala Azar  

[5 rows x 52 columns]

In [ ]:
#number of rows and column in data sets
vector_data.shape

(110, 52)

In [ ]:
#getting info about the data
vector_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110 entries, 0 to 109
Data columns (total 52 columns):
 #   Column                          Non-Null Count  Dtype 
---  ------                          --------------  ----- 
 0   sudden_fever                    110 non-null    int64 
 1   headache                        110 non-null    int64 
 2   mouth_bleed                     110 non-null    int64 
 3   nose_bleed                      110 non-null    int64 
 4   muscle_pain                     110 non-null    int64 
 5   joint_pain                      110 non-null    int64 
 6   vomiting                        110 non-null    int64 
 7   rash                            110 non-null    int64 
 8   diarrhea                        110 non-null    int64 
 9   swelling                        110 non-null    int64 
 10  nausea                          110 non-null    int64 
 11  chills                          110 non-null    int64 
 12  Muscle_cramp                    110 non-null    in

In [ ]:
#checking for missing value
vector_data.isnull().sum()

sudden_fever                      0
headache                          0
mouth_bleed                       0
nose_bleed                        0
muscle_pain                       0
joint_pain                        0
vomiting                          0
rash                              0
diarrhea                          0
swelling                          0
nausea                            0
chills                            0
Muscle_cramp                      0
digestion_trouble                 0
fatigue                           0
skin_lesions                      0
Abdominal_pain                    0
periorbital_pain                  0
neck_pain                         0
weakness                          0
back_pain                         0
weight_loss                       0
gum_bleed                         0
diziness                          0
inflammation                      0
red_eyes                          0
loss_of_appetite                  0
urination_loss              

In [ ]:
#number of catagorical data
vector_data["prognosis"].value_counts()

Chikungunya              23
Dengue                   23
Malaria                  23
Japanese encephalitis    23
Kala Azar                18
Name: prognosis, dtype: int64

Chikungunya              0
Dengue                   1
Malaria                  2
Japanese encephalitis    3
Kala Azar                4


In [ ]:
#converting the catagorical data into numarical data
#vector_data.loc[vector_data['prognosis'] == 'Chikungunya','prognosis',] = 0
#vector_data.loc[vector_data['prognosis'] == 'Dengue','prognosis',] = 1
#vector_data.loc[vector_data['prognosis'] == 'Rift Valley fever','prognosis',] = 2
#vector_data.loc[vector_data['prognosis'] == 'Yellow Fever ','prognosis',] = 3
#vector_data.loc[vector_data['prognosis'] == 'Zika  ','prognosis',] = 4
#vector_data.loc[vector_data['prognosis'] == 'Malaria  ','prognosis',] = 5
#vector_data.loc[vector_data['prognosis'] == 'Japanese encephalitis ','prognosis',] = 6
#vector_data.loc[vector_data['prognosis'] == 'West Nile fever','prognosis',] = 7
#vector_data.loc[vector_data['prognosis'] == 'Plague','prognosis',] = 8
#vector_data.loc[vector_data['prognosis'] == 'Tungiasis ','prognosis',] = 9
#vector_data.loc[vector_data['prognosis'] == 'Lyme disease','prognosis',] = 10

In [ ]:
#objet type off attribute to int64
vector_data['prognosis'] = pd.factorize(vector_data.prognosis)[0]

In [ ]:
#separete the data and levels
x =vector_data.drop(columns= 'prognosis',axis=1) #indi
y=  vector_data['prognosis'] #depen

In [ ]:
print(x)

     sudden_fever  headache  mouth_bleed  nose_bleed  muscle_pain  joint_pain  \
0               0         1            1           1            1           0   
1               1         1            1           1            1           0   
2               0         1            0           1            0           0   
3               0         0            0           0            0           1   
4               1         0            0           0            1           1   
..            ...       ...          ...         ...          ...         ...   
105             1         0            0           0            0           0   
106             0         0            0           0            0           0   
107             0         1            0           0            0           0   
108             1         1            0           0            0           0   
109             1         1            0           0            0           0   

     vomiting  rash  diarrh

In [ ]:
print(y)
y.info()

0      0
1      0
2      0
3      0
4      0
      ..
105    4
106    4
107    4
108    4
109    4
Name: prognosis, Length: 110, dtype: int64
<class 'pandas.core.series.Series'>
RangeIndex: 110 entries, 0 to 109
Series name: prognosis
Non-Null Count  Dtype
--------------  -----
110 non-null    int64
dtypes: int64(1)
memory usage: 1008.0 bytes


Splitting the train data and the test data


In [ ]:
X_train, X_test,y_train, y_test = train_test_split(x,y ,test_size=0.2,random_state=2)

In [ ]:
print(x.shape,X_train.shape, X_test.shape)
y_test.info()

(110, 51) (88, 51) (22, 51)
<class 'pandas.core.series.Series'>
Int64Index: 22 entries, 14 to 0
Series name: prognosis
Non-Null Count  Dtype
--------------  -----
22 non-null     int64
dtypes: int64(1)
memory usage: 352.0 bytes


model trenning

# **Logistic Regression Multiclass Classification**


In [ ]:
lr=LogisticRegression()

In [ ]:
lr.fit(X_train,y_train)

LogisticRegression()

In [ ]:
#predection
lr.predict(X_test)

array([0, 0, 0, 0, 1, 2, 3, 3, 0, 1, 4, 3, 4, 3, 1, 0, 1, 1, 0, 1, 0, 0])

In [ ]:
X_test

sudden_fever  headache  mouth_bleed  nose_bleed  muscle_pain  joint_pain  \
14              0         1            0           1            1           1   
13              0         1            1           1            0           0   
21              0         1            0           1            0           1   
2               0         1            0           1            0           0   
44              1         1            1           1            1           1   
48              1         1            1           1            1           0   
35              0         1            1           1            0           0   
86              0         0            0           0            1           1   
28              1         0            0           1            1           0   
36              1         0            1           0            1           1   
102             1         1            0           0            0           0   
76              0         0            0           1            1           1   
98              0         0            0           0            0           0   
78              1         0            1           0            1           0   
25              0         1            1           1            1           1   
24              1         1            0           1            1           0   
45              1         1            1           1            1           1   
29              0         1            1           1            1           1   
30              1         0            0           0            1           1   
27              0         1            1           1            1           1   
16              1         0            0           0            0           1   
0               0         1            1           1            1           0   

     vomiting  rash  diarrhea  swelling  ...  breathing_restriction  \
14          1     1         0         0  ...                      0   
13          0     0         1         0  ...                      0   
21          1     1         0         1  ...                      0   
2           1     1         0         0  ...                      0   
44          1     1         0         0  ...                      1   
48          0     1         0         0  ...                      0   
35          0     0         0         0  ...                      0   
86          0     0         1         0  ...                      0   
28          1     0         0         0  ...                      0   
36          0     0         1         1  ...                      0   
102         0     0         0         0  ...                      0   
76          1     0         0         0  ...                      0   
98          0     0         0         0  ...                      0   
78          0     0         0         0  ...                      0   
25          0     1         0         0  ...                      0   
24          1     1         0         0  ...                      0   
45          1     1         1         0  ...                      0   
29          1     0         1         0  ...                      0   
30          1     1         0         1  ...                      0   
27          1     1         1         0  ...                      0   
16          1     1         1         0  ...                      0   
0           1     0         0         0  ...                      0   

     toe_inflammation  finger_inflammation  lips_irritation  itchiness  \
14                  0                    0                0          0   
13                  0                    0                0          0   
21                  0                    0                0          0   
2                   0                    0                0          0   
44                  0                    0                0          0   
48                  0                    0                0    

train data = 100% test data = 90% =======overfitting


In [ ]:
#score of our model
#we are getting 90% accu
lr.score(X_test,y_test)

0.8181818181818182

In [ ]:
#test on train data which is giving the accu 100%

lr.score(X_train,y_train)

1.0

Chikungunya              0
Dengue                   1
Malaria                  2
Japanese encephalitis    3
Kala Azar                4



In [ ]:
lr.predict([[0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])



/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0])

In [ ]:
def get_disease_name(prediction):
    switch = {
        0: "Chikungunya",
        1: "Dengue",
        2: "Malaria",
        3: "Japanese encephalitis",
        4: "Kala Azar"
    }
    return switch.get(prediction, "Unknown Disease")

# Assuming lr is your trained machine learning model
# Replace this with your actual model prediction code
predicted_value = lr.predict([[1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.]])
disease_name = get_disease_name(predicted_value[0])
print("Predicted Disease:", disease_name)


Predicted Disease: Malaria


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [ ]:
lr.predict([[1,0,0,0,1,1,1,1,0,1,0,1,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([1])

# **Random forest**

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
# Create a Random Forest classifier
rf_classifier = RandomForestClassifier(n_estimators=100, criterion='gini',random_state=7)

# Train the classifier on the training data
rf_classifier.fit(X_train, y_train)


RandomForestClassifier(random_state=7)

In [ ]:
rf_classifier.predict(X_test)

array([0, 0, 0, 0, 1, 2, 0, 3, 0, 0, 0, 3, 4, 3, 2, 0, 1, 0, 0, 1, 0, 0])

In [ ]:
X_test

sudden_fever  headache  mouth_bleed  nose_bleed  muscle_pain  joint_pain  \
89              1         1            0           1            0           0   
91              1         0            0           0            1           0   
93              0         1            0           0            0           0   
226             1         0            0           1            0           1   
126             1         1            0           0            1           0   
243             0         0            1           1            0           0   
220             1         0            1           0            0           0   
30              1         0            0           0            1           1   
35              0         1            1           1            0           0   
139             1         0            0           1            0           0   
10              1         0            1           0            1           1   
169             1         0            0           0            0           1   
176             1         0            1           0            0           1   
230             1         0            0           1            1           1   
130             1         1            0           1            1           1   
3               0         0            0           0            0           1   
181             0         0            1           1            1           0   
175             1         0            0           0            0           0   
225             0         0            0           0            0           1   
90              0         0            0           1            0           1   
84              1         1            1           0            0           0   
134             1         1            0           1            1           1   
188             1         0            1           0            0           0   
24              1         1            0           1            1           0   
236             1         0            1           1            1           1   
156             0         0            0           1            0           1   
54              0         1            1           1            0           1   
153             1         0            0           1            1           0   
20              1         0            1           1            1           0   
101             0         0            1           1            1           0   
13              0         1            1           1            0           0   
113             0         0            1           1            0           0   
41              1         0            0           0            0           1   
221             0         0            0           0            0           0   
217             0         0            0           0            1           1   
99              0         0            0           0            0           0   
219             0         0            0           0            0           0   
23              1         1            1           1            1           1   
53              1         0            0           0            1           1   
144             1         0            1           1            0           0   
14              0         1            0           1            1           1   
166             0         0            1           1            1           0   
66              1         1            1           0            0           1   
163             0         1            0           1            0           0   
189             1         0            1           1            0           1   
227             0         0            0           0            0           1   
180             0         1            0           0            0           0   
25              0         1            1           1            1           1   
161             1         0         

In [ ]:
rf_classifier.score(X_test,y_test)

0.7727272727272727

In [ ]:
rf_classifier.score(X_train,y_train)

1.0

In [ ]:
def get_disease_name(prediction):
    switch = {
        0: "Chikungunya",
        1: "Dengue",
        2: "Malaria",
        3: "Japanese encephalitis",
        4: "Kala Azar"
    }
    return switch.get(prediction, "Unknown Disease")

# Assuming lr is your trained machine learning model
# Replace this with your actual model prediction code
predicted_value =rf_classifier.predict([[1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.]])
disease_name = get_disease_name(predicted_value[0])
print("Predicted Disease:", disease_name)

Predicted Disease: Malaria


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [ ]:
rf_classifier.predict([[1,0,0,0,1,1,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]])
rf_classifier.predict([[1,0,0,0,1,1,1,1,0,1,0,1,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1])

In [ ]:
rf_classifier.predict([[1,0,0,0,1,1,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]])
rf_classifier.predict([[1,0,0,0,1,1,1,1,0,1,0,1,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1])

In [ ]:
rf_classifier.predict([[1,0,0,0,1,1,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]])
rf_classifier.predict([[1,0,0,0,1,1,1,1,0,1,0,1,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1])

In [ ]:
#for attribute selection imp
#feature_imp= pd.Series(rf_classifier.feature_importances_,index=vector_data.feature_names).sort_values(ascending=False)

In [ ]:
rf_classifier.predict([[1,1,1,1,0,1,0,1,0,1,0,0,1,1,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([2])

In [ ]:
rf_classifier.predict([[1,1,0,1,1,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,1,0,1,0,1,0,1,1,0,0,1,1,1,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0	]])#give input

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([3])